version: '3.8'
services:
  auth-service:
    build:
      context: ./authApp
      dockerfile: Dockerfile
    container_name: auth-service
    command: "uvicorn app.core.main:main_app --reload --workers 1 --host 0.0.0.0 --port 8004"
    env_file:
      - ./authApp/.env
    ports:
    - 8004:8004

networks:
  default:
    external: true
    name: kghomesnet