version: '3.8'
services:
  auth-service:
    build:
      context: ./authApp
      dockerfile: Dockerfile
    container_name: auth-service
    volumes:
      - ./authApp:/authApp
    command: "uvicorn app.core.main:main_app --reload --workers 1 --host 0.0.0.0 --port 8001"
    env_file:
      - ./authApp/.env
    ports:
    - 8001:8001

networks:
  default:
    external: true
    name: kghomesnet